SET IDENTITY_INSERT Establecimientos ON;
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (1,'DIRECCIÓN NACIONAL',2,24,'DN',1);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (2,'UNIDAD 31 - CENTRO FEDERAL DE DETENCION DE MUJERES “NUESTRA SEÑORA DEL ROSARIO DE SAN NICOLAS”',1,1,'U 31',2);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (3,'CPF III - COMPLEJO PENITENCIARIO FEDERAL III - NOA',17,8,'CPF III',3);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (4,'UNIDAD 16 - INSTITUTO PENITENCIARIO FEDERAL DE SALTA "SEÑOR Y VIRGEN DEL MILAGRO”',17,5,'U 16',4);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (5,'UNIDAD 23 - CÁRCEL FEDERAL DE SALTA',17,30,'U 23',5);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (6,'UNIDAD 22 - CARCEL FEDERAL DE JUJUY',10,17,'U 22',6);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (7,'UNIDAD 8 - INSTITUTO PENITENCIARIO FEDERAL "NUESTRA SRA.DEL ROSARIO DE RIO BCO. Y PAYPAYA"',10,17,'U 08',7);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (8,'EPN - ESCUELA PENITENCIARIA DE LA NACION "DR. JUAN JOSÉ O´CONNOR"',1,1,'EPN',8);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (9,'UNIDAD 35 - INSTITUTO PENAL FEDERAL COLONIA PINTO',22,16,'U 35',9);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (10,'UNIDAD 7 - PRISION REGIONAL DEL NORTE',4,13,'U 07',10);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (11,'UNIDAD 4 - COLONIA PENAL DE SANTA ROSA',11,18,'U 04',11);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (12,'UNIDAD 13 - INSTITUTO CORRECCIONAL DE MUJERES “NUESTRA SEÑORA DEL CARMEN”',11,18,'U 13',12);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (13,'UNIDAD 25 - INSTITUTO CORRECCIONAL ABIERTO DE GENERAL PICO',11,9,'U 25',13);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (14,'UNIDAD 30 - INSTITUTO DE JÓVENES ADULTOS',11,18,'U 30',14);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (15,'CPF IV - COMPLEJO PENITENCIARIO FEDERAL IV DE MUJERES - EZEIZA',1,1,'CPF IV',15);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (16,'UNIDAD 19 - COLONIA PENAL DE EZEIZA',1,1,'U 19',16);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (17,'DIRECCION DE TRASLADOS',2,24,'Dir. Traslados',18);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (18,'UNIDAD 28 - CENTRO DE DETENCIÓN JUDICIAL',2,24,'U 28',21);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (19,'UNIDAD 21 - CENTRO PENITENCIARIO DE ENFERMEDADES INFECCIOSAS',2,24,'U 21',22);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (20,'CFJA - COMPLEJO FEDERAL DE JÓVENES ADULTOS',1,2,'CFJA',23);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (21,'UNIDAD 18 - CASA DE PREEGRESO “DR. JOSÉ INGENIEROS”',2,24,'U 18',24);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (22,'UNIDAD 14 - CÁRCEL DE ESQUEL "SUBALCAIDE ABEL ROSARIO MUÑOZ"',5,6,'U 14',25);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (23,'UNIDAD 5 - COLONIA PENAL DE GENERAL ROCA',16,10,'U 05',26);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (24,'UNIDAD 9 - PRISION REGIONAL DEL SUR',15,29,'U 09',27);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (25,'UNIDAD 32 - CENTRO DE DETENCION JUDICAL DE MENDOZA',13,28,'U 32',29);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (26,'CPF I - COMPLEJO PENITENCIARIO FEDERAL I',1,1,'CPF I',30);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (27,'UNIDAD 6 - INSTITUTO DE SEGURIDAD Y RESOCIALIZACION',5,12,'U 06',31);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (28,'HPC I -HOSPITAL PENITENCIARIO CENTRAL I',1,1,'HPC I',32);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (29,'CPF CABA - COMPLEJO PENITENCIARIO FEDERAL DE LA CIUDAD AUTONOMA DE BUENOS AIRES (DEVOTO)',2,24,'CPF CABA',33);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (30,'HPC II - HOSPITAL PENITENCIARIO CENTRAL II',2,24,'HPC II',34);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (31,'UNIDAD 10 - CARCEL DE FORMOSA',9,7,'U 10',35);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (32,'UNIDAD 11 - COLONIA PENAL DE PRESIDENCIA ROQUE SAENZ PEÑA',4,14,'U 11',36);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (33,'UNIDAD 17 - COLONIA PENAL DE CANDELARIA',14,4,'U 17',37);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (34,'UNIDAD 12 - COLONIA PENAL VIEDMA',16,20,'U 12',38);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (35,'UNIDAD 15 - CARCEL DE RIO GALLEGOS',20,15,'U 15',39);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (36,'CPF II - COMPLEJO PENITENCIARIO FEDERAL II',1,2,'CPF II',40);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (37,'UNIDAD 33 - INSTITUTO ABIERTO DE PREEGRESO NUESTRA SRA. DEL VALLE - Ezeiza',1,1,'U 33',42);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (38,'UNIDAD 34 - INSTITUTO PENAL FEDERAL DE CAMPO DE MAYO',1,3,'U 34',43);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (39,'ESCUELA DE SUBOFICIALES "SUBDIRECTOR NACIONAL JUAN CARLOS GARCIA BASALO"',1,1,'Esc. Subof',47);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (40,'CPF V - COMPLEJO PENITENCIARIO FEDERAL V - SENILLOSA',15,19,'CPF V',48);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (41,'CPF VI - COMPLEJO PENITENCIARIO FEDERAL VI DE CUYO',13,11,'CPF VI',49);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (42,'DEPARTAMENTO DE ESTADISTICA, CENSO E INVESTIGACION OPERATIVA',2,24,'DECIO',87);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (43,'DEPARTAMENTO DE ESTUDIOS Y PROYECTOS',2,24,'DEyP',95);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (44,'DIRECCION DE VISITAS, RELACIONES FAMILIARES Y SOCIALES',2,24,'Dir. Visita',117);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (45,'ENTE DE COOPERACION TECNICA Y FINANCIERA DEL S.P.F.',2,24,'Encope',127);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (46,'DRyP - DIRECCION DE RETIROS Y PENSIONES',2,24,'DRyP',141);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (47,'DTyP - DIRECCION DE TRABAJO Y PRODUCCION',2,24,'DTyP',142);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (48,'DIRECCION GENERAL DE ADMINISTRACION',2,24,'DGA',143);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (49,'DEPARTAMENTO DE IMPLEMENTACION DE SOLUCIONES TECNOLOGICAS',2,24,'Dpto. Implementación',147);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (50,'DIRECCION DE EDUCACION, CULTURA Y DEPORTE',2,24,'Dir. Educación',149);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (51,'DIRECCION DE RECURSOS HUMANOS',2,24,'Dir. RR.HH.',157);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (52,'DIRECCION PRINCIPAL DE OPERACIONES PENITENCIARIAS',1,1,'DPoP',158);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (53,'DEPARTAMENTO DE ASUNTOS INTERNOS',2,24,'DAI',160);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (54,'DIRECCION DE SECRETARIA GENERAL',2,24,'DSG',165);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (55,'DIRECCION PRINCIPAL DE INSTITUTOS DE FORMACION DEL PERSONAL',1,1,'Dir. Inst. Formacion ',169);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (56,'DIRECCION DE AUDITORIA GENERAL',2,24,'Dir. Aud. Gral.',171);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (57,'DIRECCION DE COORDINACION DE LA SUBDIRECCION NACIONAL',2,24,'DCoor',174);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (58,'DIRECCION DE BIENESTAR DEL PERSONAL',1,1,'Dir. Bienestar',175);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (59,'DIRECCION DE SANIDAD',2,24,'Dir. Sanidad',176);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (60,'DIRECCION PRINCIPAL ANALISIS DE LA INFORMACION',2,24,'DPAI',178);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (61,'DIRECCION DE PROTECCION CONTRA SINIESTROS Y SEGURIDAD LABORAL',1,1,'Dir. Prot. Stros.',181);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (62,'DIRECCION DE JUDICIAL',2,24,'Dir. Judicial',183);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (63,'DIRECCION DE OBRA SOCIAL',2,24,'DOS',184);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (64,'SUBDIRECCION NACIONAL',2,24,'SDN',185);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (65,'DIRECCION DE CRIMINOLOGIA',2,24,'Dir. Crim.',186);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (66,'DIRECCION GENERAL DEL CUERPO PENITENCIARIO',2,24,'DGCP',187);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (67,'JEFATURA REGION METROPOLITANA',2,24,'Jef. Reg. Metropolitana',193);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (68,'SERVICIO PSIQUIATRICO PARA VARONES',1,1,'SPV',195);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (69,'DIRECCION DE ASISTENCIA SOCIAL',2,24,'DAS',197);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (70,'DIRECCION ACADEMIA SUPERIOR DE ESTUDIOS PENITENCIARIOS "D. ROBERTO PETTINATO"',2,24,'ASEP',198);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (71,'DIRECCION DE AUDITORIA CONTABLE',2,24,'DAC',199);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (72,'SERVICIO DE REDUCCION DE VIOLENCIA',1,1,'Serv. Reducción Violencia',200);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (73,'DIRECCION DE CONTADURIA Y FINANZAS',2,24,'Dir. Cont. Y Finanzas',201);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (74,'DIRECCION DE SEGURIDAD PENITENCIARIA',1,1,'DSP',202);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (75,'DIRECCION DE CONTRATACIONES',2,24,'Dir. Contrataciones',203);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (76,'UNIDAD 29 - ALCAIDIA PENAL FEDERAL',2,24,'U 29',204);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (77,'DEPARTAMENTO DE CULTO',2,24,'D. Culto',205);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (78,'DIRECCION DE PRESUPUESTO',2,24,'D. Presupuesto',207);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (79,'SERVICIO PSIQUIATRICO PARA MUJERES',1,1,'Serv. Psiq. Mujeres',208);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (80,'INSTITUTO DE CRIMINOLOGIA',2,24,'Inst. Crim.',209);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (81,'ALCAIDIA FEDERAL DE CORDOBA',6,25,'Alc. Cordoba',211);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (82,'DIRECCION GENERAL DE REGIMEN CORRECCIONAL',2,24,'DGRC',212);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (83,'SERVICIO DE MONITOREO E INSPECCION DE ESTABLECIMIENTOS PENITENCIARIOS',2,24,'SMIEP',213);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (84,'DIRECCION DE TESORERIA',2,24,'D. Tesoreria',214);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (85,'CONSEJO DE PLANIFICACION Y COORDINACION',2,24,'Consejo Planificación',215);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (86,'JEFATURA REGION SUR',2,24,'Jef. Reg. Sur',216);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (87,'DEPARTAMENTO DE INFORMATICA Y COMUNICACIONES',2,24,'DIyC',217);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (88,'UNIDAD 24 - INSTITUTO FEDERAL DE JOVENES ADULTOS',1,2,'U 24',218);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (89,'ALCAIDIA FEDERAL DE LOMAS DE ZAMORA',1,22,'Alc. Lomas',219);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (90,'DIRECCION PRINCIPAL DE TRATO Y TRATAMIENTO',2,24,'DTyT',220);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (91,'SERVICIO DE PROMOCION DE DERECHOS HUMANOS',2,24,'Serv. Promocion DH',221);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (92,'UNIDAD 26 - INSTITUTO PARA JOVENES ADULTOS "DR. JUAN CARLOS LANDO"',2,24,'U 26',222);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (93,'SERVICIO DE PREVENCION DE LA CORRUPCION',2,24,'Serv. Prev. Corrupcion',223);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (94,'SERVICIO DE SUSTENTABILIDAD AMBIENTAL Y GESTION DEL RIESGO DE DESASTRES',1,1,'Serv. Sust. Amb.',224);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (95,'ALCAIDIA FEDERAL DE LA PLATA',1,21,'Alc. La Plata',225);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (96,'Ministerio de Justicia y Derechos Humanos',2,24,'Min. Jus. Y DDHH',226);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (97,'OTROS ORGANISMOS (ADSCRIPTOS EXTRA-INSTITUCIONALM.)',25,26,'Otros Organismos',227);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (98,'EX DIRECCION DE SEGURIDAD Y TRASLADOS',2,24,'Ex. Dir. Seg. Trasl.',228);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (99,'DIRECCION PRINCIPAL DE PERSONAL',2,24,'DPP',229);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (100,'INSTITUTO DE CLASIFICACION Y CATEGORIZACION',2,24,'ICyC',230);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (101,'JEFATURA REGION CENTRO',2,24,'Jef. Reg. Centro',231);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (102,'EX-CARCEL DE ENCAUSADOS DE LA CAPITAL FEDERAL',2,24,'Ex. Carcel Encausados CABA',232);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (103,'SERVICIO PSIQUIATRICO CENTRAL DE VARONES',2,24,'Serv. Psi. Varones',233);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (104,'SERVICIO PSIQUIATRICO CENTRAL DE MUJERES',2,24,'Serv. Psi. Mujeres',234);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (105,'ALCAIDIA PENAL CORONEL (R.E.) MIGUEL ANGEL PAIVA',2,24,'Alc. Paiva',235);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (106,'ALCAIDIA CORRECCIONAL JUNCAL',2,24,'Alc. Juncal',236);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (107,'SERVICIO CENTRAL DE ALCAIDÍAS',2,24,'Central de Alcaidias',237);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (108,'DIRECCION DE ANALISIS DE INFORMACION PENITENCIARIA',2,24,'DAIP',238);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (109,'DEPARTAMENTO DE INVESTIGACION JUDICIAL',2,24,'Dpto. Inv. Jud.',239);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (110,'CPF VII - COMPLEJO PENITENCIARIO FEDERAL VII',1,1,'CPF VII',240);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (111,'UNIDAD 36 – CÁRCEL FEDERAL DE CORONDA "DR. EUSEBIO GÓMEZ"',21,27,'U 36',241);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (112,'DIRECCION DE COORD. DEL SIST. INT. DE GESTION PARA PERS. PRIV. DE LA LIB. DE ALTO RIESGO EN EL SPF',2,24,'SIGPPLAR',242);
INSERT INTO Establecimientos (Id, Nombre, ProvinciaId, LocalidadId, Alias, TadId) VALUES (113,'Ministerio de Seguridad',2,24,'Min. Seg.',243);
SET IDENTITY_INSERT Establecimientos OFF;