SET IDENTITY_INSERT Provincias ON;
INSERT INTO Provincias (Id, Nombre) VALUES (1, 'Buenos Aires');
INSERT INTO Provincias (Id, Nombre) VALUES (2, 'Ciudad Autónoma de Buenos Aires');
INSERT INTO Provincias (Id, Nombre) VALUES (3, 'Catamarca');
INSERT INTO Provincias (Id, Nombre) VALUES (4, 'Chaco');
INSERT INTO Provincias (Id, Nombre) VALUES (5, 'Chubut');
INSERT INTO Provincias (Id, Nombre) VALUES (6, 'Córdoba');
INSERT INTO Provincias (Id, Nombre) VALUES (7, 'Corrientes');
INSERT INTO Provincias (Id, Nombre) VALUES (8, 'Entre Ríos');
INSERT INTO Provincias (Id, Nombre) VALUES (9, 'Formosa');
INSERT INTO Provincias (Id, Nombre) VALUES (10, 'Jujuy');
INSERT INTO Provincias (Id, Nombre) VALUES (11, 'La Pampa');
INSERT INTO Provincias (Id, Nombre) VALUES (12, 'La Rioja');
INSERT INTO Provincias (Id, Nombre) VALUES (13, 'Mendoza');
INSERT INTO Provincias (Id, Nombre) VALUES (14, 'Misiones');
INSERT INTO Provincias (Id, Nombre) VALUES (15, 'Neuquén');
INSERT INTO Provincias (Id, Nombre) VALUES (16, 'Río Negro');
INSERT INTO Provincias (Id, Nombre) VALUES (17, 'Salta');
INSERT INTO Provincias (Id, Nombre) VALUES (18, 'San Juan');
INSERT INTO Provincias (Id, Nombre) VALUES (19, 'San Luis');
INSERT INTO Provincias (Id, Nombre) VALUES (20, 'Santa Cruz');
INSERT INTO Provincias (Id, Nombre) VALUES (21, 'Santa Fe');
INSERT INTO Provincias (Id, Nombre) VALUES (22, 'Santiago del Estero');
INSERT INTO Provincias (Id, Nombre) VALUES (23, 'Tierra del Fuego');
INSERT INTO Provincias (Id, Nombre) VALUES (24, 'Tucumán');
INSERT INTO Provincias (Id, Nombre) VALUES (25, 'Otros');
SET IDENTITY_INSERT Provincias OFF;
