// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sicom.Dominio.Context;

#nullable disable

namespace Sicom.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250902160451_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiComSPF.Models.Agente", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Credencial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstablecimientoId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Funcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agentes");
                });

            modelBuilder.Entity("SiComSPF.Models.Establecimiento", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LocalidadId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProvinciaId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("TadId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Establecimientos");
                });

            modelBuilder.Entity("SiComSPF.Models.EstadoLinea", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosLineas");
                });

            modelBuilder.Entity("SiComSPF.Models.LineaAdministrativa", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<decimal>("EstablecimientoId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("EstadoLineaId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ModalidadId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ModuloId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("MotivoBaja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroInterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroLinea")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("OrigenServicioId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("PabellonId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("PrestadorServicioId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UbicacionFinal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("EstadoLineaId");

                    b.HasIndex("ModalidadId");

                    b.HasIndex("ModuloId");

                    b.HasIndex("OrigenServicioId");

                    b.HasIndex("PabellonId");

                    b.HasIndex("PrestadorServicioId");

                    b.ToTable("LineasAdministrativas");
                });

            modelBuilder.Entity("SiComSPF.Models.LineaCelular", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("AgenteId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<decimal>("EstablecimientoId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("EstadoLineaId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Imei")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("MarcaId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ModeloId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("MotivoBaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PlanContratado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrestadorServicioId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Sim")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("UbicacionFinal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("EstadoLineaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("PrestadorServicioId");

                    b.ToTable("LineasCelulares");
                });

            modelBuilder.Entity("SiComSPF.Models.LineaPublica", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<decimal>("EstablecimientoId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("EstadoLineaId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ModalidadId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ModuloId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("MotivoBaja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroLinea")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("OrigenServicioId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("PabellonId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("PrestadorServicioId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("TipoEquipoTelefonicoId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UbicacionFinal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("EstadoLineaId");

                    b.HasIndex("ModalidadId");

                    b.HasIndex("ModuloId");

                    b.HasIndex("OrigenServicioId");

                    b.HasIndex("PabellonId");

                    b.HasIndex("PrestadorServicioId");

                    b.HasIndex("TipoEquipoTelefonicoId");

                    b.ToTable("LineasPublicas");
                });

            modelBuilder.Entity("SiComSPF.Models.Localidad", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProvinciaId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("SiComSPF.Models.MarcaCelular", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MarcasCelulares");
                });

            modelBuilder.Entity("SiComSPF.Models.ModalidadLinea", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModalidadesLineas");
                });

            modelBuilder.Entity("SiComSPF.Models.ModeloCelular", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MarcaCelularId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaCelularId");

                    b.ToTable("ModelosCelulares");
                });

            modelBuilder.Entity("SiComSPF.Models.Modulo", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("EstablecimientoId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("SiComSPF.Models.Observacion", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("AgenteId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LineaAdministrativaId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("LineaCelularId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("LineaPublicaId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("LineaAdministrativaId");

                    b.HasIndex("LineaCelularId");

                    b.HasIndex("LineaPublicaId");

                    b.ToTable("Observaciones");
                });

            modelBuilder.Entity("SiComSPF.Models.OrigenServicio", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrigenesServicios");
                });

            modelBuilder.Entity("SiComSPF.Models.Pabellon", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("EstablecimientoId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ModuloId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PoblacionPenal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Pabellones");
                });

            modelBuilder.Entity("SiComSPF.Models.PrestadorServicio", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrestadoresServicios");
                });

            modelBuilder.Entity("SiComSPF.Models.Provincia", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("SiComSPF.Models.TipoEquipoTelefonico", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposEquiposTelefonicos");
                });

            modelBuilder.Entity("SiComSPF.Models.LineaAdministrativa", b =>
                {
                    b.HasOne("SiComSPF.Models.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.EstadoLinea", "EstadoLinea")
                        .WithMany()
                        .HasForeignKey("EstadoLineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.ModalidadLinea", "Modalidad")
                        .WithMany()
                        .HasForeignKey("ModalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.OrigenServicio", "OrigenServicio")
                        .WithMany()
                        .HasForeignKey("OrigenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.Pabellon", "Pabellon")
                        .WithMany()
                        .HasForeignKey("PabellonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.PrestadorServicio", "PrestadorServicio")
                        .WithMany()
                        .HasForeignKey("PrestadorServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establecimiento");

                    b.Navigation("EstadoLinea");

                    b.Navigation("Modalidad");

                    b.Navigation("Modulo");

                    b.Navigation("OrigenServicio");

                    b.Navigation("Pabellon");

                    b.Navigation("PrestadorServicio");
                });

            modelBuilder.Entity("SiComSPF.Models.LineaCelular", b =>
                {
                    b.HasOne("SiComSPF.Models.Agente", "Agente")
                        .WithMany("LineasCelulares")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.EstadoLinea", "EstadoLinea")
                        .WithMany()
                        .HasForeignKey("EstadoLineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.MarcaCelular", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.ModeloCelular", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.PrestadorServicio", "PrestadorServicio")
                        .WithMany()
                        .HasForeignKey("PrestadorServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Establecimiento");

                    b.Navigation("EstadoLinea");

                    b.Navigation("Marca");

                    b.Navigation("Modelo");

                    b.Navigation("PrestadorServicio");
                });

            modelBuilder.Entity("SiComSPF.Models.LineaPublica", b =>
                {
                    b.HasOne("SiComSPF.Models.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.EstadoLinea", "EstadoLinea")
                        .WithMany()
                        .HasForeignKey("EstadoLineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.ModalidadLinea", "Modalidad")
                        .WithMany()
                        .HasForeignKey("ModalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.OrigenServicio", "OrigenServicio")
                        .WithMany()
                        .HasForeignKey("OrigenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.Pabellon", "Pabellon")
                        .WithMany()
                        .HasForeignKey("PabellonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.PrestadorServicio", "PrestadorServicio")
                        .WithMany()
                        .HasForeignKey("PrestadorServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.TipoEquipoTelefonico", "TipoEquipoTelefonico")
                        .WithMany()
                        .HasForeignKey("TipoEquipoTelefonicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establecimiento");

                    b.Navigation("EstadoLinea");

                    b.Navigation("Modalidad");

                    b.Navigation("Modulo");

                    b.Navigation("OrigenServicio");

                    b.Navigation("Pabellon");

                    b.Navigation("PrestadorServicio");

                    b.Navigation("TipoEquipoTelefonico");
                });

            modelBuilder.Entity("SiComSPF.Models.Localidad", b =>
                {
                    b.HasOne("SiComSPF.Models.Provincia", null)
                        .WithMany("Localidades")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiComSPF.Models.ModeloCelular", b =>
                {
                    b.HasOne("SiComSPF.Models.MarcaCelular", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaCelularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("SiComSPF.Models.Modulo", b =>
                {
                    b.HasOne("SiComSPF.Models.Establecimiento", null)
                        .WithMany("Modulos")
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiComSPF.Models.Observacion", b =>
                {
                    b.HasOne("SiComSPF.Models.Agente", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiComSPF.Models.LineaAdministrativa", "LineaAdministrativa")
                        .WithMany("Observaciones")
                        .HasForeignKey("LineaAdministrativaId");

                    b.HasOne("SiComSPF.Models.LineaCelular", "LineaCelular")
                        .WithMany("Observaciones")
                        .HasForeignKey("LineaCelularId");

                    b.HasOne("SiComSPF.Models.LineaPublica", "LineaPublica")
                        .WithMany("Observaciones")
                        .HasForeignKey("LineaPublicaId");

                    b.Navigation("Agente");

                    b.Navigation("LineaAdministrativa");

                    b.Navigation("LineaCelular");

                    b.Navigation("LineaPublica");
                });

            modelBuilder.Entity("SiComSPF.Models.Pabellon", b =>
                {
                    b.HasOne("SiComSPF.Models.Modulo", null)
                        .WithMany("Pabellones")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiComSPF.Models.Agente", b =>
                {
                    b.Navigation("LineasCelulares");
                });

            modelBuilder.Entity("SiComSPF.Models.Establecimiento", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("SiComSPF.Models.LineaAdministrativa", b =>
                {
                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("SiComSPF.Models.LineaCelular", b =>
                {
                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("SiComSPF.Models.LineaPublica", b =>
                {
                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("SiComSPF.Models.MarcaCelular", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("SiComSPF.Models.Modulo", b =>
                {
                    b.Navigation("Pabellones");
                });

            modelBuilder.Entity("SiComSPF.Models.Provincia", b =>
                {
                    b.Navigation("Localidades");
                });
#pragma warning restore 612, 618
        }
    }
}
